In [2]:
# Importing the libraries

import numpy as np
import pandas as pd
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [3]:
# Import the IRIS Dataset

from sklearn.datasets import load_iris
iris = load_iris(as_frame=True)

In [4]:
# Printing 
print(iris)

{'data':      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns], 'target': 0      0
1      0
2 

In [5]:
X = iris.data

# Setting the classes as either virginica (1) or Non-Virginica (0)
y = iris.target_names[iris.target] == 'virginica' 

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.75, random_state=42) 

In [6]:
# Logistic Regression Model Building and Training

log_reg = LogisticRegression(random_state=42)
log_reg.fit(X_train, y_train)

LogisticRegression(random_state=42)

In [7]:
# Predicting the results for X_test data

y_pred = log_reg.predict(X_test)

Checking instances in the test set that were misclassfied by the logistic regression model.

In [8]:
y_pred

array([False, False,  True, False, False, False, False,  True, False,
       False,  True, False, False, False, False, False,  True, False,
       False,  True, False,  True, False,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False,  True,
       False, False])

In [9]:
y_test

array([False, False,  True, False, False, False, False,  True, False,
       False,  True, False, False, False, False, False,  True, False,
       False,  True, False,  True, False,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False,  True,
       False, False])

As we can notice in this model has correctly classifed per test set.All predictions matched the true labels.There are no failure modes.

In this case,there are no misclassified instances.The model performed perfect on this test set.There are no shared properties to analyze.

In [10]:
# Calculate the accuracy of the model

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print(accuracy)

1.0


Accuracy = 1.0 indicates 100% accurate model. There a no False predictions with this model. This implies that for any given X feature matrix values, the logistic regression model is predicting the accurate results with certainty. 

In [11]:
# Confusion matrix formation

from sklearn.metrics import confusion_matrix

conf_matr = confusion_matrix(y_test, y_pred)

conf_matr

array([[26,  0],
       [ 0, 12]], dtype=int64)

The above confusion matrix has no False Positives and no False Negatives. This indicates that the model predictions are perfectly accurate.

In [12]:
# Finding the precision score the logistic regression model

from sklearn.metrics import precision_score

prec_score = precision_score(y_test, y_pred)

prec_score

1.0

This indicates out of all predicted positive values, all of the values of True Positives. This is consistent with the confusion matrix.

In [13]:
# Calculating the recall for the logistic regression model

from sklearn.metrics import recall_score

recall = recall_score(y_test, y_pred)

recall

1.0

Recall = 1 means out of all actual True values, the model predicted 100% correctly.